version: '3'

services:
  api-cherished:
    build:
      dockerfile: Dockerfile.dev
      context: .
    command: ["npm", "run", "dev"]
    container_name: "api-cherished"
    depends_on:
      - mongodb
    env_file:
      - ./.env
    environment:
      - JWT_SECRET=$JWT_SECRET
      - MONGO_TEST=$MONGO_TEST
      - MONGO_URI=$MONGO_URI
      - NODE_ENV=$NODE_ENV
      - PORT=$PORT
      - S3_ACCESS_KEY_ID=$S3_ACCESS_KEY_ID
      - S3_SECRET_ACCESS_KEY=$S3_SECRET_ACCESS_KEY
      - S3_BUCKET=$S3_BUCKET
      - S3_BUCKET_KEY=$S3_BUCKET_KEY
      - URI=$URI
    ports:
      - "4000:4000"
    restart: unless-stopped
    volumes:
      - api_node_modules:/app/node_modules
      - .:/app

  mongodb:
    image: mongo
    container_name: "mongodb"
    env_file:
      - ./.env
    ports:
      - "27017-27019:27017-27019"
    restart: unless-stopped
    volumes:
      - data-mongodb:/data/db

volumes:
  data-mongodb:
  api_node_modules:
