name: CI

on:
  push:
    branches: [ master, staging ]
  pull_request:
    branches: [ master, staging ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Environment
        run: cp .env.ci .env

      - name: Build
        run: docker-compose up --build -d

      - name: Test
        run: docker exec -t api-cherished npm run test
